name: Log Commits to Discord

on: 
  push:
    branches:
      - main

jobs:
  log_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Send Commit Data to Discord
        run: |
          COMMIT_COUNT=$(echo '${{ toJson(github.event.commits) }}' | jq '. | length')
          MESSAGE=""

          if [ "$COMMIT_COUNT" -eq 1 ]; then
            MESSAGE="1 new commit"
          else
            MESSAGE="$COMMIT_COUNT new commits"
          fi

          DESCRIPTION=""

          for i in $(seq 0 $(($COMMIT_COUNT - 1))); do
            COMMIT_MESSAGE=$(echo '${{ toJson(github.event.commits) }}' | jq -r ".[$i].message")
            COMMIT_URL=$(echo '${{ toJson(github.event.commits) }}' | jq -r ".[$i].url")
            DESCRIPTION+="\`[$(echo $COMMIT_URL | cut -d '/' -f 7-9)]($COMMIT_URL)\` - $COMMIT_MESSAGE\n"
          done

          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{
              "username": "GitHub",
              "embeds": [{
                "title": "[${{ github.repository }}:${{ github.ref_name }}] '"$MESSAGE"'",
                "description": "'"$DESCRIPTION"'",
                "color": 5814783
              }]
            }' \
            https://discord.com/api/webhooks/1285249000123011084/I0lTJuGkb6keUpunnqykUsX2fKH1QApPy30fhEuMssYAeP9l2nbojnONPdpLVbwDXU5N
