name: Log Commits to Discord

on: 
  push:
    branches:
      - main

jobs:
  log_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Send Commit Data to Discord
        run: |
          COMMIT_COUNT=$(echo '${{ toJson(github.event.commits) }}' | jq '. | length')
          MESSAGE=""

          if [ "$COMMIT_COUNT" -eq 1 ]; then
            MESSAGE="1 new commit"
          else
            MESSAGE="$COMMIT_COUNT new commits"
          fi

          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{
              "username": "GitHub",
              "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "embeds": [{
                "title": "[${{ github.repository }}:${{ github.ref_name }}] '"$MESSAGE"'",
                "description": "`${{ github.event.head_commit.id }}` - ${{ github.event.head_commit.message }}",
                "url": "${{ github.event.head_commit.url }}",
                "color": 5814783
              }]
            }' \
            "${{ secrets.DISCORD_WEBHOOK_URL }}"
