name: Log Commits to Discord

on: push

jobs:
  log_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Send Commit Data to Discord
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"New commit pushed by ${{ github.actor }}: ${{ github.event.head_commit.message }}\"}" \
            https://discord.com/api/webhooks/1285249000123011084/I0lTJuGkb6keUpunnqykUsX2fKH1QApPy30fhEuMssYAeP9l2nbojnONPdpLVbwDXU5N
